- name: MY PLAYBOOK
  hosts: bigips
  connection: local
  gather_facts: no
  
  vars:
    uri_method: POST

  vars_files:
  - ../creds/bigip_cred.yaml

  tasks:

  - name: AS3 Deploy
    uri:
      url: "https://{{inventory_hostname}}/mgmt/shared/appsvcs/declare/"
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: "{{uri_method}}"
      body: "{{ lookup('file','as3_declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_response

  - name: DEBUG AS3 OUTPUT
    debug:
      msg: "{{as3_response}}"